
application: marcial-languages
version: python-docs-insertion
runtime: python27
api_version: 1
threadsafe: true

# To make it a managed vm uncomment below
#application: cloud-support-sbt-test
#vm: true
#manual_scaling:
#  instances: 1
#vm_settings:
#  machine_type: n1-standard-1


builtins:
- appstats: on
- remote_api: on

handlers:

- url: /.*
  script: app.webapp

libraries:
- name: lxml
  version: "latest"
- name: PIL
  version: "latest"
- name: webapp2
  version: "2.3"
